### ISSUE TITLE
Symlinks are not restored or restored incorectly in latest version

### ISSUE THREAD

**Issue by lafriks** [meltwater/drone-cache#105]
When using `:latest` tag restored `node_modules` and after npm install, npm scripts using `npm run xxx` does work correctly.
After switching to docker tag `:master-ef42beb` it does fail to either restore `node_modules/.bin/...` folder or symlinks correctly.
I also checked the created tar file content on S3 storage and it does contain `.bin` folder with symlink files so I'm not really sure where it goes wrong.

~~*NB* On so not too important note, also cached tar file content seems to have changed structure between `:latest` and `:master-ef42beb` and cached tar files fails to restore with error if tar file was created with `:latest` but extracting is done using `:master-ef42beb` version (should I report that separately?). I just deleted all cached objects so that was not so big deal :)~~

**Comment by kakkoyun** [comment]
Thanks for the great feedback and testing it. I will investigate the symbolic link issue.

> NB On so not too important note, also cached tar file content seems to have changed structure between :latest and :master-ef42beb and cached tar files fails to restore with error if tar file was created with :latest but extracting is done using :master-ef42beb version (should I report that separately?). I just deleted all cached objects so that was not so big deal :)

That would be greater if you can also open an issue for that. It means we kind of break backwards compatibility, worth looking.

**Comment by lafriks** [comment]
Added debug steps and seems `node_modules/.bin` folder is empty
![image](https://user-images.githubusercontent.com/165205/78777215-d0eb5280-79a1-11ea-97f6-297a718e4048.png)

**Comment by lafriks** [comment]
Tested and works like a charm :)
