### ISSUE TITLE
The links in the README section "Supported Storage Backends" don't work

### ISSUE THREAD

**Issue by spier** [meltwater/drone-cache#113]
**Describe the bug**
The links in the README section about **Supported Storage Backends** are not working.
See https://github.com/meltwater/drone-cache#supported-storage-backends

**To Reproduce**
1. Open https://github.com/meltwater/drone-cache#supported-storage-backends in your browser
2. Click any of the links
3. I am redirected to `https://github.com/meltwater/drone-cache#` 

**Expected behavior**
The respective links open. 

I don't know if these links are meant to point to internal drone-cache documentation, or docs about the respective storage engines on other websites?

**Comment by spier** [comment]
I would be happy to fix this, if I only knew where these links are meant to point to :)
Looks like this section of the README got introduced in 2a4334d7?

**Comment by kakkoyun** [comment]
Thanks for opening this, it'll help me to keep track of the issue.

I have forgotten to commit those files. I want to introduce them with https://github.com/meltwater/drone-cache/pull/108

Soon we will be launching nice documentation through github-pages, it is under construction.


![](https://media3.giphy.com/media/EIiJp9cQ3GeEU/giphy.gif?cid=5a38a5a287692ea297bc4659ea6174712a27819857b2c263&rid=giphy.gif)

**Comment by kakkoyun** [comment]
Closing this one for sake of https://github.com/meltwater/drone-cache/issues/99
