### ISSUE TITLE
Looking for co-maintainers

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#116]
As the sole active maintainer, I'm looking for co-maintainers for the project to push features faster.
Please ping me if you're interested. 

It'd be awesome if you have already contributed to the project and interested. Otherwise, there would be a brief probation period after starting contributing to the project.

**Comment by jimsheldon** [comment]
Hey @kakkoyun 

Our team is keeping an eye on issues opened in this repository, we are happy to help.

We have some automation watching issues in this repo.  How do you think we could best contribute?

**Comment by kakkoyun** [comment]
Hey @jimsheldon, thanks for reaching out. Any type of help is appreciated. But mostly I need a contributor who gets their hands dirty more often.

And I'm going to start a documentation page and probably I could use help for the documentation. Lower barrier of entry.

Last but not least, testing the release candidates always is appreciated https://github.com/meltwater/drone-cache/releases/tag/v1.1.0-rc0. If you can check the latest release candidate on your pipelines and open issues for the discovered things would be great at this stage.

Cheers

**Comment by jimsheldon** [comment]
Hey @kakkoyun, we have discussed this as a team.  For any issue where you would like our help, can you please ping @omarwashington, he is our Product Owner.

We can then prioritize the work through our normal processes.

Thanks!

**Comment by NotMoni** [comment]
@kakkoyun I am willing to help. Feel free to contact me. 🦄

**Comment by pastushenkoy** [comment]
> Last but not least, testing the release candidates always is appreciated https://github.com/meltwater/drone-cache/releases/tag/v1.1.0-rc0. If you can check the latest release candidate on your pipelines and open issues for the discovered things would be great at this stage.

Is there a simple way to get this RC from meltwater docker repository? As far as I see publishing is disabled in GoReleaser

![image](https://user-images.githubusercontent.com/22550728/82905317-664f9f80-9f6c-11ea-88a5-286c9beb9fc8.png)

**Comment by kakkoyun** [comment]
@pastushenkoy We don't push images for release candidates. However, you're right we should push RCs to repo for convenience. Could you please open an issue for this? I'll look into it.
