### ISSUE TITLE
Add support for page upload for azure

### ISSUE THREAD

**Issue by pastushenkoy** [meltwater/drone-cache#118]
**Is your feature request related to a problem? Please describe.**
When building frontends, cache sizes can easily exceed 256 Mb limit Azure sets for Put method. In this case Azure returns 413 and refuses to upload blob.

**Describe the solution you'd like**
PagePut method can be used. There is an API in azure for such kind of situations. Unfortunately, api requires slice of bytes for PagePut so cache must be read to memory. 

**Describe alternatives you've considered**
I couldn't find any workarounds.

**Additional context**

**Comment by kakkoyun** [comment]
@pastushenkoy for reporting and already proposing a possible solution (https://github.com/meltwater/drone-cache/pull/119) to this issue.

As I've already comment on the PR, we shall fix this without breaking the streaming upload.

**Comment by pastushenkoy** [comment]
It turned out that the latest azure client fixes my problem, but I didn't have chance to check it because release candidates are not pushed into the registry.

They definitely should :)
