### ISSUE TITLE
New version of gcs fake breaks tests

### ISSUE THREAD

**Issue by pastushenkoy** [meltwater/drone-cache#120]
**Describe the bug**
The new version of fsouza/fake-gcs-server (1.19) breaks plugin tests.

**To Reproduce**
Just clone master, start docker-compose and run tests.

**Expected behavior**
Tests passed.

**Desktop (please complete the following information):**
 - OS: MacOs catalina

**Comment by kakkoyun** [comment]
@pastushenkoy Thanks for reporting this.
It'd be great if we can fix this in a separate PR.

For more context: https://github.com/meltwater/drone-cache/pull/119/files#r429900969
