### ISSUE TITLE
Push every built version of plugin to docker hub

### ISSUE THREAD

**Issue by pastushenkoy** [meltwater/drone-cache#122]
**Is your feature request related to a problem? Please describe.**

Containers of non-release builds are not pushed into docker hub. This makes development and debugging difficult as I cannot use my builds in my pipelines.

**Describe the solution you'd like**

It would be cool if EVERY build was pushed to registry. If so, it allows testing new features without setting up my own build in my repo.

**Comment by pastushenkoy** [comment]
@kakkoyun The obvious solution here is to enable `skip_push: auto` in `.goreleaser.yml` to `false`. I can make pull request if it suits you.

**Comment by kakkoyun** [comment]
@pastushenkoy of course, go ahead. I just want to be sure that we only push something to registry only we create a tag.

**Comment by pastushenkoy** [comment]
I'm trying to find approach to publish minor tags without affecting the `latest` tag in docker registry and I don't see any way to do it with goreleaser as publishing tool. As goreleaser can only have one `.goreleaser.yml` and only one `dockers` section in this file, there is no possibility to customize container tags for specific release.

Don't you think that publishing with drone is better approach?

**Comment by kakkoyun** [comment]
@pastushenkoy Thanks for the discussion. I found this extremely healthy for the sake of this project.

1. I get your reasoning and we have convenient `make container` and `make container-push` with an overridable parameter for contributors to test their changes on their own pipeline. Just change the variable to point your own publicly accessible registry an it'd do the rest.
It's not the upstream project's responsibility build and push images each and every commit/tag. Even having and image for each merge to master is noisy. I'll stick with tagging only certain branches.

2. It's definitely not ok. The `latest` should only point the latest stable release. Users have a tendency to use the plugins without a tag (e.g `meltwater/drone-cache`) in their pipelines. In such cases it pulls the `latest`, that means if we push a release candidate with a bug and `latest` points this candidate, we'll break users' pipelines. This is not what we want. We need to find a workaround to this.

Today I have a bit of free time, I can work on this project. Tell me if you need my help.

**Comment by kakkoyun** [comment]
An example of a snapshot release https://github.com/meltwater/drone-cache/releases/tag/v1.1.0-rc1

In the documentation and contributing I'll document pushing images from local machine.
