### ISSUE TITLE
Enable absolute path mode

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#130]
**Is your feature request related to a problem? Please describe.**
There is a need to cache certain directories outside the workspace. As it described in https://github.com/meltwater/drone-cache/issues/106#issuecomment-643086789

**Describe the solution you'd like**
Introduce a mode to enable absolute path mode if a given mount path starts with `/`.

cc @cmays20

**Comment by hacktron95** [comment]
hello @kakkoyun and good day, please assign me.
