### ISSUE TITLE
Provide an arm image

### ISSUE THREAD

**Issue by kolaente** [meltwater/drone-cache#146]
**Is your feature request related to a problem? Please describe.**
I am packaging my application in arm docker images and am looking to cache the build dependencies to speed up the build, especially since the arm runner is slow. However, this plugin is only available for amd64, not arm.

**Describe the solution you'd like**
I'd love to have arm images for the plugin so I can use it on the arm runner.

**Describe alternatives you've considered**
I'm not aware of any. If you know some please let me know.

**Comment by kakkoyun** [comment]
@kolaente Thanks for the issue. When I have first tried this (months ago) we had issues with a couple of dependencies. That being said, we can give it another try and if needed we can get rid of problematic dependency (of course if it's not vital). This shouldn't be hard. One just need to enable it in and resolve the issues https://github.com/meltwater/drone-cache/blob/master/.goreleaser.yml

I'm happy to accept contributions. Help wanted.

**Comment by jimsheldon** [comment]
With [v1.2.0](https://github.com/meltwater/drone-cache/releases/tag/v1.2.0) are now publishing an arm64 docker image. Please give it a try and let us know if you find any problems.

**Comment by jimsheldon** [comment]
Reopening this since it seems the arm64 image contains the amd64 binary, I'll update when I have a fix

**Comment by jimsheldon** [comment]
I pushed a fix and released https://github.com/meltwater/drone-cache/releases/tag/v1.2.1

Please give it a try
