### ISSUE TITLE
Support zstd compression

### ISSUE THREAD

**Issue by Alexis211** [meltwater/drone-cache#156]
**Is your feature request related to a problem? Please describe.**
I'm using drone-cache for a Rust project to cache the `target` directory, which contains compiled modules for all of my project's dependencies, so that the pipeline doesn't have to rebuild everything from scratch (it takes a looong time!). Unfortunately the `target` directory tends to grow very large (often several GBs), so I'd like to compress it. The `gzip` compression provided by drone-cache is pretty good, but gzip has relatively bad performance compared to more modern solutions.

**Describe the solution you'd like**
`zstd` is a state-of-the-art compression algorihtm that runs at least twice as fast as gzip and has slightly better compression ratios (with default settings). Here is an example on a 1Mb chunk of a file which is representative of the Rust binaries I have in my `target` directory:

```
alex@io:/tmp$ time gzip -k 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d

real    0m0.031s
user    0m0.027s
sys     0m0.004s


alex@io:/tmp$ time zstd 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d
06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d : 12.29%   (1048576 => 128844 bytes, 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d.zst)

real    0m0.017s
user    0m0.012s
sys     0m0.005s
```

```
-rw-r--r--  1 alex alex 1.0M Feb  9 16:17 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d
-rw-r--r--  1 alex alex 131K Feb  9 16:17 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d.gz
-rw-r--r--  1 alex alex 126K Feb  9 16:17 06d34fc780f4f60549600af1d472510744092c2fb070b304ae75a23e0e88804d.zst
```

It would be nice to have `zstd` as an option in `drone-cache`'s `archive_format` option.

**Describe alternatives you've considered**
I'm storing my cache archives on a custom implementation of S3 ([Garage](https://git.deuxfleurs.fr/deuxfleurs/Garage)), and am currently considering implementing compression in Garage itself. I will probably do it anyways, but there are still advantages to having a good compression algorithm in `drone-cache` itself:

- less bandwidth used to store files on S3 or S3-like backends
- reduce costs by using less space (since S3 bills per space used)

**Comment by kakkoyun** [comment]
@Alexis211 It'd be nice to have this an additional method. Help wanted, PRs are more than welcome!
