### ISSUE TITLE
Add more architectures for the docker image

### ISSUE THREAD

**Issue by celedev97** [meltwater/drone-cache#160]
**Is your feature request related to a problem? Please describe.**
I'd love to use this plugin in a raspberry pi 4, but the architecture is arm64, while the only architecture for the docker image is amd64.
Running the image from arm64 result in this:
```
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Describe the solution you'd like**
Build and publish the image for more architectures.

**Comment by jimsheldon** [comment]
Hello @fcdev, we have added a arm64 docker image in v1.2.0 https://github.com/meltwater/drone-cache/releases/tag/v1.2.0

Please give it a try and write back with any feedback. Thanks!

**Comment by jimsheldon** [comment]
My mistake, the arm64 image is not working as expected. I will update this when it has been fixed.

**Comment by jimsheldon** [comment]
https://github.com/meltwater/drone-cache/releases/tag/v1.2.1 has been released which fixes the arm64 docker image. Please give it a try.

**Comment by jimsheldon** [comment]
The arm64 build is now available, closing this out.
