### ISSUE TITLE
Support passing multiple files to the `checksum` function

### ISSUE THREAD

**Issue by ste93cry** [meltwater/drone-cache#196]
**Is your feature request related to a problem? Please describe.**
While trying to mimick the functionality of the `actions/cache` GitHub Action, I found out that the `checksum` function needed to customize the cache key does not support multiple files

**Describe the solution you'd like**
The input argument of the `checksum` function should be changed so that it accepts multiple strings. It would also be cool if the file paths could be specified as glob

**Describe alternatives you've considered**
A new function with a new name (GitHub calls it `hashFiles`) would be more appropriate and self-explanatory than the current name. The old one could be marked as deprecated and removed in the next major version

**Comment by kakkoyun** [comment]
This looks like something, we can have. Do you want to give it a try?

**Comment by ste93cry** [comment]
Sure, I've submitted a PR 😃

**Comment by bdebyl** [comment]
Further discussion in comments of https://github.com/meltwater/drone-cache/pull/198
