### ISSUE TITLE
Migrate CI tasks to Github Actions

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#199]
- Keep the end to end tests on drone.io public offering
- Since the company behind drone.io sold. The free public offering is not stable, I would suggest to utilize github actions for suitable tasks

**Comment by hikerspath** [comment]
We are working with Harness on this, stability has returned for our test-cases.  Keeping this open for tracking / monitoring though

**Comment by bdebyl** [comment]
Drone CI still seems to work quite well as of today. There are some issues I've discussed with GitHub actions and there isn't a clear advantage I can see here. Given that one can self-host Drone and the cloud offered Drone we are able to utilize are working perfectly I don't see a strong argument for the level of effort needed here. Will also keep this open for tracking, but unless issues arise with Drone this most likely will not be implemented.

**Comment by hikerspath** [comment]
Closing issue, will revisit and reference if required.
