### ISSUE TITLE
Doublestar support in mount array

### ISSUE THREAD

**Issue by PaulRill00** [meltwater/drone-cache#206]
**Is your feature request related to a problem? Please describe.**
When working with mono-repo's caching dependencies might be tedious. So instead of mounting every subfolder and it's dependencies, allow for generic folder selection.

For example, if one has a folder structure like:
```
root
  package.json
  node_modules
  packages
    package1:
      package.json
      node_modules
      dist
    package2:
      package.json
      node_modules
      dist
```
Let's say you want to cache all `node_modules` and `dist` folders, without having to require all those folders in the `mount` array separately. 

**Describe the solution you'd like**
Support generic folder mounting like:
```
mount:
  - "node_modules"
  - "packages/**/node_modules"
  - "packages/**/dist"
```

A dependency that might help solve the issue: https://github.com/bmatcuk/doublestar

**Describe alternatives you've considered**
You could also go with a regex alternative, but the one above seems more straight forward.

**Additional context**
- None -

**Comment by bdebyl** [comment]
This looks like a fun quick feature, I'll look at adding it now for the next release

**Comment by bdebyl** [comment]
Implemented as part of https://github.com/meltwater/drone-cache/pull/209
