### ISSUE TITLE
Move releases from GitHub Actions to Drone CI

### ISSUE THREAD

**Issue by bdebyl** [meltwater/drone-cache#219]
**Is your feature request related to a problem? Please describe.**
There are no specific problems with having Goreleaser, or releases in general part of GitHub Actions, but it does mean maintaining both GitHub Actions pipelines and Drone CI pipelines for a single repository.

**Describe the solution you'd like**
Simply move the release steps related to `drone-cache` from GitHub Actions to Drone CI steps

**Describe alternatives you've considered**
Keeping it in GitHub Actions is certainly a possibility, though it will continue to add operational overhead in maintaining two separate tools that are able to do the same tasks. Simplifying these down to a single CI tool such as Drone CI would be best.

**Additional context**
None, all discussion and feedback is welcome here.

**Comment by spier** [comment]
@bdebyl would open source contributors have access to build information in Drone as well? 
Similar to what they can see in the GitHub Actions output today?

**Comment by bdebyl** [comment]
@spier are you able to see the Drone CI build outputs from the commits [here](https://cloud.drone.io/meltwater/drone-cache/630)? If so then yes.

The only step that's used by GitHub Actions is Goreleaser, which I assume was used with Actions as it has more straightforward release creation than what one might see in Drone CI for GitHub.

Beyond that I don't see any advantage in maintaining two separate CI platforms.

**Comment by spier** [comment]
@bdebyl I looked at the output in an incognito browser window, and yes, I can see it.
Excellent, so meltwater org membership isn't required for that.

Thanks for exploring this with me :)

**Comment by bdebyl** [comment]
Seems like GITHUB_TOKEN is an automatically generated and managed secret as part of Action workflows.

Read more [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)

This means that Action workflows are unique in not requiring explicit secrets for generating a release and can use the natively baked in ones. So far I have been unable to find anything in Drone CI that does something similar, and a manually token would need to be generated which is not ideal.

Closing this due to the handy and secure functionality that GitHub Actions allows vs. lack of such functionality from Drone CI. Will re-open if Drone adds support for something like this with the GitHub plugin.
