### ISSUE TITLE
Checksum does not appear to read file contents

### ISSUE THREAD

**Issue by surzycki** [meltwater/drone-cache#34]
I have an entry similar to this in the settings for the cache-key template

```
cache-key:  bundle-dependencies--{{ checksum "Gemfile.lock" }}
```

However, no matter the contents of that file, the cache key is always:

```
196ca0330c1f62e2a1a047a2.....
```

**Comment by kakkoyun** [comment]
Hello @surzycki, could you please try with "cache_key" instead of "cache-key"? Apparently, we have made a mistake on our prime example, I will fix it immediately.

**Comment by surzycki** [comment]
That would be it ! thnks !

**Comment by kakkoyun** [comment]
Documentation fixed.
