### ISSUE TITLE
Filesystem example is misleading

### ISSUE THREAD

**Issue by cdvv7788** [meltwater/drone-cache#40]
The filesystem example has the following:

```
volumes:
  - name: cache
    temp: {}
```

However, according to [drone docs](https://docs.drone.io/user-guide/pipeline/volumes/) a temp folder is for sharing information between steps, not builds.

To circumvent this, I had to use:

```
volumes:
  - name: cache
    host:
      path: /var/lib/cache 
```

This, however, has the restriction of requiring the repository to be trusted. After doing that, everything worked as expected.

There is nothing wrong with the project functionality per se, but the examples and documentation can be improved to better explain the alternatives, and to avoid contradictions.
Other than this, everything worked smoothly. Nice plugin!

**Comment by kakkoyun** [comment]
@cdvv7788 Thanks a lot for reporting. I will improve the documentation.

**Comment by jimsheldon** [comment]
#59 should fix this

@kakkoyun can you review?
