### ISSUE TITLE
Update Drone plugin index

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#44]
Update https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md

* [ ] Generate DOCS.md from usage and examples
* [ ] Clone local DOCS.md to repo (open a PR?)
* [ ] Automate process

**Comment by kakkoyun** [comment]
This should be done after next major release.

**Comment by bdebyl** [comment]
The new workflow from Drone has changed for linking to index documentation link to the README and similar. See the README of the master branch to find information on the new method.
