### ISSUE TITLE
Not saving .bin when caching node_modules on filesystem

### ISSUE THREAD

**Issue by cdvv7788** [meltwater/drone-cache#48]
## Expected Behavior
.bin is kept, so symlinks are not lost

## Actual Behavior
.bin folder is nowhere to be found

## Steps to Reproduce the Problem

  1. Create node_modules and install packages that symlink binaries into node_modules/.bin (i.e. jest)
  2. Rebuild cache
  3. Restore cache in another build
  4. Try to execute symlinked commands from restored cache

## Specifications

  - Version: dev
  - Platform: Ubuntu 18
  - Subsystem:

I am not sure if this is something that can be done at the cache level, but I am putting it in here in case that someone else has the same situation as me.
After restoring cache, I am unable to run anything that npm install added on the first run. The .bin folder where all the symlinks for node_modules are stored is missing after the restore.

My guesses (wild guesses, as I haven't checked any implementation) are:
1. Hidden folders are not being added to the archive
2. Symlinks are not being added to the archive

My workaround was to add the final file directly. In my case I was using jest:
- ./node_modules/jest/bin/jest.js

**Comment by kakkoyun** [comment]
Hey @cdvv7788, have you checked this issue #39 and related fix #42? I thought I have fixed it.
I'm not sure sure which state is `dev` in. Could please test it with the latest stable version as well?

Thanks in advance.

**Comment by kakkoyun** [comment]
@cdvv7788 Is this still an issue?

**Comment by cdvv7788** [comment]
Sorry. Still haven't had the time to check it. I will do that tomorrow.

**Comment by cdvv7788** [comment]
@kakkoyun I tested with the :latest and it worked. Thanks!
