### ISSUE TITLE
Add SFTP Storage Backend

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#60]
Define a new backend for the plugin to support FTP

**Comment by alexisvisco** [comment]
I would work on this.

I will use this library to dial with ftp/s:
https://github.com/jlaffaye/ftp

Have you any objection ?

**Comment by kakkoyun** [comment]
Hey @alexisvisco, that would be great. We love community contributions.

I wouldn't say objection but if I were you, I'd go with https://github.com/pkg/sftp. It's a very well maintained package with more contributors and activity. Also for the packages from `github.com/pkg` we may say defacto standard from the community. 

In this repo, we tried to keep everything as "pure" as possible. We only used packages from the standard library, standard extended library (golang.org/x/..) and `github.com/pkg`. For the vendor integrations like AWS, we used their own SDK. Probably the only exception is the CLI framework package which comes from the original drone plugin template. I'd really appreciate if we keep it that way.

That being said, I'd really like to see your contributions on this one. Feel free to send PR, I'd be happy to review it.

**Comment by alexisvisco** [comment]
I should have done my homework better, google did not offer it to me haha.

I will using  https://github.com/pkg/sftp, I will also start a [WIP] pull request tomorrow.

**Comment by kakkoyun** [comment]
Fixed by #68.

**Comment by kakkoyun** [comment]
This feature is not released yet, it is available with the tag `master-43bce02` though.
Use `meltwater/drone-cache:master-43bce02` as image to test.
