### ISSUE TITLE
 Add Google Cloud Storage Backend

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#61]
Create a new backend implementation to support GCP Object storage

**Comment by A-Hilaly** [comment]
Hello, can work on this one ?

**Comment by kakkoyun** [comment]
Hello @A-Hilaly, of course, go ahead! You can bother me if you need anything. I'd be happy to review your work. 

We already have interfaces and conventions in place to add a new back-end. You can have a look at https://github.com/meltwater/drone-cache/blob/master/cache/backend/s3.go to kickstart things.

**Comment by A-Hilaly** [comment]
Nice 👍 ! Thanks for the tip @kakkoyun i'm going to open a PR soon

**Comment by spier** [comment]
I am doing some documentation cleanup, so adding this link here.

This issue is about integrating with https://cloud.google.com/storage/

**Comment by A-Hilaly** [comment]
@kakkoyun while implementing this backend, i realised that Cloud Storage Go client need a `context.Context` for read/write operations. `aws-go-sdk` has also methods that uses context like `PutObjectWithContext`. 

I had toughs about changing the Backend interface to allow context propagation with something like: 

```go
type Backend interface {
	Get(context.Context, string) (io.ReadCloser, error)
	Put(context.Context, string, io.ReadSeeker) error
}
```
Anyways this will certainly force changes all over the backends/plugin/main and need to be discussed/implemented in a separate PR. 

I'm still not sure if context cancellation can be useful at this stage, but i think it can be a great feature, especially when dealing with huge objects.

**Comment by kakkoyun** [comment]
@A-Hilaly That's a good idea. I'm also a fan of `context`s nowadays. After we merge a couple of backend implementations, we can change the interface and refactor, accordingly if this emerges as a pattern.
