### ISSUE TITLE
 Add Azure Storage Backend

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#62]
Create a new backend to support Microsoft Azure Object storage.

**Comment by spier** [comment]
See https://azure.microsoft.com/en-in/services/storage/

**Comment by akashsharma95** [comment]
Would like to take this up

**Comment by spier** [comment]
That would be awesome @akashsharma95! Let us know if you need help.

**Comment by kakkoyun** [comment]
@akashsharma95 if you haven't started this one, please take a look at #76. It'd be awesome to use `go-cloud` for this.

**Comment by spier** [comment]
@akashsharma95 the maintainers of this repo discussed this issue today, and @limayekaiwalya would like to get started on this, as a way for him to get onboarded onto the project.

He will get started soon, so if you have done any work already, would you mind sharing that in a draft PR or similar?
