### ISSUE TITLE
Add Red Hat Ceph Storage Backend

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#63]
Create a new backend to support red Hat Object storage.

**Comment by spier** [comment]
@kakkoyun can you add a link to the storage backend that you are referring to here?

**Comment by kakkoyun** [comment]
See https://www.redhat.com/en/technologies/storage/ceph for mentioned storage, and check https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/developer_guide/ceph-object-gateway-s3-api for technical details.

**Comment by kakkoyun** [comment]
Shares the same interface with S3, nothing to do. Just needs to be documented as support backend.
