### ISSUE TITLE
Do you plan to support not only tar, but also rsync based copy

### ISSUE THREAD

**Issue by vtolstov** [meltwater/drone-cache#66]
**Is your feature request related to a problem? Please describe.**
if cache dir contains only some big files best to use rsync to it and not use tar

**Describe the solution you'd like**
ability to rsync files between cache and build volume

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by spier** [comment]
Hi @vtolstov and thanks for reaching out.

Can you describe what the problem is that you are currently experiencing? i.e. is drone-cache not working for you at all, or are builds slow, are what are you experiencing?

Also what file size are we talking about here? 100 MB? 500MB? 1GB?

**Comment by vtolstov** [comment]
I have big dvd iso files that needs to be cached.
Pack 4-6 this files to tar not needed, So i simple need rsync

**Comment by kakkoyun** [comment]
@vtolstov I definitely get the use case, unfortunately, it's not in our plans in near future. However, we had other reported issues about uploading large files (#55), we could consider this approach if large files become a big problem.

Again, that being said if you are willing to bite the bullet and work on this,  as long as we agree on a design and come up with an API that won't break existing behaviour, I'm ok with it. Please go ahead. I'm happy to help with implementation and review.

**Comment by spier** [comment]
We just discussed this issue internally and decided that we won't implement the requested `rsync based copy` as it would move drone-cache away from its core purpose.

Thanks for the idea though and please keep contributing if you like drone-cache :)
