### ISSUE TITLE
Add TTL to cache archives

### ISSUE THREAD

**Issue by kakkoyun** [meltwater/drone-cache#70]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to set a time-to-live to archives when they are cached.

**Describe the solution you'd like**
Whenever an archive's TTL expires, the archive should automatically expire.

**Comment by kakkoyun** [comment]
We can provide this feature if storage backend provides this feature.

**Comment by kakkoyun** [comment]
For AWS S3 following could be a good starting point: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutBucketLifecycle

**Comment by jimsheldon** [comment]
Sorry for letting this linger so long.

We feel this capability is best managed in the backend itself. As @kakkoyun said, S3 supports lifecycle management. Other backends have similar capabilities.
