### ISSUE TITLE
Feature request: log gzip compression ratio

### ISSUE THREAD

**Issue by Beanow** [meltwater/drone-cache#72]
**Is your feature request related to a problem? Please describe.**
Currently I'm investigating a slowdown in the caching steps for a build. I'm aware the data being cached has grown significantly, so I wondered how "just tar" vs tar with gzip would perform.

Turns out, tar without gzip performed worse because I was getting a whopping 80% size reduction.

**Describe the solution you'd like**
In the archiving (and extraction?) steps, I would like to see an additional line that prints out the gzip compression ratio achieved.

**Describe alternatives you've considered**
Duplicate the caching steps, modify the copy to use tar at a different cache key, compare filesizes at the backend (in my case minio's GUI).

**Additional context**
Example build with and without gzip.
https://drone.teamopen.dev/teamopen-dev/sourcecred-stack-lookup/79

Results in the layers:
```
# With gzip
.scores 72.84 MB
.sourcecred 768.31 MB

# Without gzip
.scores 535.22 MB
.sourcecred 3.61 GB
```

**Comment by kakkoyun** [comment]
@Beanow Thanks a lot for reporting this. It's not very hard to achieve this. I'll add a line in debug logs. I have plans to improve logging in the backlog anyway.

Would it be useful to have the ability to configure the compression level?

**Comment by Beanow** [comment]
> Would it be useful to have the ability to configure the compression level?

For this particular problem. I don't think so.
Both that 3.6GB archive and the 535MB one, has currently 122 logical divisions inside it. The majority of which I don't need every build. So the ability to manage the cache more dynamically is what I need in this case.

**Comment by kakkoyun** [comment]
Hey @Beanow, with the latest snapshot, when debug mode enabled you can see compression level.  Also, you can specify it if you wish.

Check out `docker pull meltwater/drone-cache:master-50833a8`

Please feel free to ping me if you observe any issues.

**Comment by Beanow** [comment]
#84 adds a log message for the used gzip compression level parameter. However what I meant was the _actually achieved compression ratio_. As this depends a lot on what kind of data you're storing, it helps to inform whether the time spent compressing is worth it for this particular cache.

For instance if you're getting a 1% reduction but spend 4 minutes doing so, probably better to not gzip. But if like my case you get 80% reduction, you'll likely want compression.

**Comment by kakkoyun** [comment]
@Beanow Ahaa, thanks for the clarification. I was a bit hasty with the implementation. I will re-open it again.

I will add a logline that prints out the ratio of input bytes and output bytes, and the time it takes in the process.
