### ISSUE TITLE
Cache is always rebuilding

### ISSUE THREAD

**Issue by andreyvital** [meltwater/drone-cache#83]
The cache is currently always being rebuilt for me—I think we should compute the `cache_key` in the rebuild process, and if it has changed then we rebuild.

```
cache_key: {{ checksum "yarn.lock" }}
```

That's my `cache_key`—if the lock file hasn't changed (hence the key is the same), there's no need to re-upload `node_modules` entirely.

If implemented, should also check if the cache for the given key exists. Otherwise, it's the first time we're generating it.

Thoughts?

**Comment by andreyvital** [comment]
It'd shave off 2 minutes off build time for me haha. I can try to implement it later on—but not guaranteed! For now I am hoping you can implement @kakkoyun 😅

**Comment by emersonf** [comment]
Is there documentation for the `rebuild` step? I'd like to find out how the cache key is used to determine what to do and whether paths are being checked for changes.

As a template, CircleCi's documentation on `save_cache` has a nice diagram that makes it clear when to expect when caches are saved. (See the [bottom of the blue Workflow Run 2 and Workflow Run 3 boxes in the documentation](https://circleci.com/docs/2.0/caching/#caching-libraries).)
