### ISSUE TITLE
Cache cannot rebuid properly when nested paths specified in mount

### ISSUE THREAD

**Issue by dmitweb** [meltwater/drone-cache#87]
**Describe the bug**
I try cache yarn.lock file, but when it's extracted from tar it md5 checksum different. This leads to reinstall node_modules dependencies.

**To Reproduce**
1. Check md5sum before cache and after extract.

**Expected behavior**
md5sum file before and after must match

**Maintainer's note:**
> Rebuild step fails to find files when nested path given:
> `packages/test/node_modules`

**Comment by kakkoyun** [comment]
@dmitweb Thanks for the feedback.

Have you actually checked the checksum of this manually by comparing them before and after? I just want to be sure that yarn or npm doesn't intercept in anyhow.

It'd be great if you can provide a simple case to reproduce this, maybe something public?

**Comment by dmitweb** [comment]
@kakkoyun 

> Have you actually checked the checksum of this manually by comparing them before and after? I just want to be sure that yarn or npm doesn't intercept in anyhow.

Yes, i checked them. First screenshot from reproduce, second screenshot from my app. Code that check checksum is same. After many tests, I realized that the main problem with caching nested paths. Below i provide repo reproduce issue.

![1](https://user-images.githubusercontent.com/5724174/71848149-cc33ab80-30df-11ea-8d5d-ff85f04ab20f.png)

![2](https://user-images.githubusercontent.com/5724174/71848298-2b91bb80-30e0-11ea-87f9-ff4a446ebb73.png)

Normal case: after first run drone pipeline, result must be cached and first yarn install must echo
success Already up-to-date.

Repo: after first run drone pipeline, yarn install command reinstall deps

ps. if comment line packages/test/node_modules from mount (restore, rebuild) all works fine, but in my project i have much many deps in package.json, and some of them install in packages/test/node_modules, so i must cache this folder too, this leads to diff in checksums, btw i don't know why

https://github.com/dmitweb/drone-cache-bug

I hope you can figure it out

**Comment by kakkoyun** [comment]
@dmitweb Thank you very much for your elaborate response. I'll look into it and do my best to figure it out.

**Comment by kakkoyun** [comment]
@dmitweb I know it's been a while, finally, I've got a fix candidate https://github.com/dmitweb/drone-cache-bug/pull/1

**Comment by kakkoyun** [comment]
Feel free to open this one again if the latest version doesn't solve your problem. It'll be in the next release otherwise.
