### ISSUE TITLE
More complex rule to cache mounted files

### ISSUE THREAD

**Issue by mr-cn** [meltwater/drone-cache#91]
**Is your feature request related to a problem? Please describe.**
I manage my C++ project 3rd-party dependencies by CMake, and it stores the 3rd-party source files in a structure like this (and seems hard to change):
```
.
├── ... (my source code)
├── cmake-build-debug
│   ├── _deps
│   │   ├── lib1-build
│   │   ├── lib1-src
│   │   ├── lib1-subbuild
│   │   ├── lib2-build
│   │   ├── lib2-src
│   │   └── lib2-subbuild (or more libs)
│   ├── .... (other files which we don't need to cache)
```

The `libxxx-src` is what need to cache, and `libxxx-build` and `libxxx-subbuild` is what don't need (and can't cache).

But it seems I can only cache the entire `_deps` directory. (If there is any way, please tell me)

**Describe the solution you'd like**
Maybe we can support wildcards (like `*-src`) to select them?

**Comment by kakkoyun** [comment]
Hello @mr-cn ,

To be honest, I haven't tried to cache individual files and I don't recall if we explicitly check if the given mount path is a directory or not. We might be feeding that path directly to archiver. (So I will check it). You can also give it a try, `mount` is a list so try putting those paths in there individually.
```
  mount:
    - '_deps/lib1-src'
    - '_deps/lib2-src'
```
OR,

you can always add manual steps to your CI pipeline. So after you build your dependencies, just copy them over to a different directory, `cp -r *-src dep_cache`. Then mount this directory at the drone-cache stage. And before your build step check if you already have things in `dep_cache` and basically copy them to `_dep`, `cp dep_cache/*-src _dep/`.

I know they both are tedious jobs, I'm just proposing this as a workaround.

That being said, I like the idea of specifying regexes in mount paths. I'll consider this.

**Comment by mr-cn** [comment]
Thank you for your reply. 

I searched a lot these days, and got these:

1. I didn't test if `mount` supports a list. But whether or not, we can set a symbol link for the `*-src` files to store them in a individual directory.

2. CMake is able to change the path of `-build` and `-subbuild`, which I didn't notice before.

So, sorry for bothering...

**Comment by kakkoyun** [comment]
@mr-cn  All good. Thanks a lot anyway, I'll try to implement regexes.
