### ISSUE TITLE
Kubernetes PVC as a Cache Volume

### ISSUE THREAD

**Issue by danilorsilva** [meltwater/drone-cache#96]
Hello all,

     Is there a way to mount a pvc on drone to cache files?

     I found how to set a local volume (file system) as a cache but i would like to use a kubernetes pvc to storage cache files.

Thanks!

**Comment by kakkoyun** [comment]
@danilorsilva Hello, thanks for the question. However, this is not the correct place to ask this question.  

You have to ask it in https://gitter.im/drone/drone or open an issue at https://github.com/drone/drone. 

`drone-cache` is just a plugin (i.e a container intended to run as a pipeline step) to the https://github.com/drone/drone, it doesn't handle anything related to running infrastructure such as volumes etc.  You can also check drone runner documentation https://docs.drone.io/runner/kubernetes/overview/.

I hope this helps.
