### ISSUE TITLE
Customize cache key with path

### ISSUE THREAD

**Issue by sunbing81** [meltwater/drone-cache#97]
The final cache path is generated by joining repo name and cache key ([here](https://github.com/meltwater/drone-cache/blob/50c33170f01195f7900e8f6457b1b8fe0dc4d53b/plugin/plugin.go#L173) & [here](https://github.com/meltwater/drone-cache/blob/50c33170f01195f7900e8f6457b1b8fe0dc4d53b/plugin/plugin.go#L148)). This prevents end users to fully control the cache destination (basically the structure is somewhat fixed: <bucket>/<repo_name>/<cache key>).

Wonder if the user could control it freely.

Regards.

**Comment by kakkoyun** [comment]
@sunbing81 thanks for reaching out, I don’t see any reason not to. We can add a new flag to override default behaviour. It’s a small change. 

Feel free to send over a PR if you feel like it 🤗

**Comment by kakkoyun** [comment]
@sunbing81 as you can check in https://github.com/meltwater/drone-cache/commit/7198420a55f4346c27a182a0743d000e4d0238f0 with `remote_root` you can configure that variable now. It'll be on the next release.
